# Generated by Django 5.1.3 on 2024-11-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_to_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_genre',
        ),
    ]
